[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bllonfig"
version = "0.1.0"
dependencies = [
]
dynamic = [
    "description",
    "requires-python",
    "authors",
    "classifiers"
]